services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQLDB_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQLDB_USER=$MYSQL_USER
      - MYSQLDB_PASSWORD=$MYSQL_PASSWORD
      - MYSQLDB_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 30s
      retries: 1

  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: posts-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : 
        "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
